# .github/workflows/uptime-bot.yml
name: Uptime Bot

on:
  workflow_dispatch:  # يُطلق من خارجي عبر GitHub API

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Load .env
        env:
          URLS: ${{ secrets.URLS }}
        run: |
          echo "URLS=\"$URLS\"" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Run uptime ping
        run: npm run ping
