name: Uptime Bot

on:
  schedule:
    # كل 10 دقائق
    - cron:  '*/10 * * * *'
  workflow_dispatch:  # خيار لتشغيله يدوياً من واجهة GitHub

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Load .env
        env:
          URLS: ${{ secrets.URLS }}
          TIMEOUT_MS: ${{ secrets.TIMEOUT_MS }}
        run: |
          echo "URLS=\"$URLS\"" >> .env
          echo "TIMEOUT_MS=$TIMEOUT_MS" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Run uptime ping
        run: npm run ping
