# .github/workflows/uptime-bot.yml

name: Uptime Bot

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Load .env from multiple secrets
        run: |
          echo "URLS=\"$URL1 $URL2 $URL3\"" >> .env
        env:
          URL1: ${{ secrets.URL1 }}
          URL2: ${{ secrets.URL2 }}
          URL3: ${{ secrets.URL3 }}

      - name: Install dependencies
        run: npm ci

      - name: Run uptime ping
        run: npm run ping
